package io.github.Yuryh1.exception;

public class PedidoNaoEncontradoException extends RuntimeException{

    public  PedidoNaoEncontradoException(){
    super("pedido nao encontrado");
    }
}
